### PR TITLE
[V3 Linux]  Calling dialogs on main thread

### LINKED ISSUE #3378: [V3 Linux Bug] Tracking down Linux Dialog panics
### Description

At the moment the `Open File` or any dialog in the `/v3/examples/dialogs` either panics or gives and exit status 1. 
I've dug into it to try and find the issue and i'm stuck here with the following error
```shell
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
```
It appears the gtk isnt executing the dialog on the main thread as it is supposed to. However there isnt really any other symtoms of the methods of dispatching to the main threads have issues and looking through those functions i dont see any glaring issues so posting here to see if other eyes can solve the problem. It errors in fairly inconsistent ways which does hint towards an issue executing on the main thread (see screenshots for various ways it has exited)

### To Reproduce

1. Run the dialogs example
2. Click the `Open File`
3. Wails will exit with either an XLib, XCB, or status 1 error. There's been no consistent means to reproduce a certain exit... see screenshots. Reattempting these steps will likely result in a few of the errors i've listed in screenshots.

### Expected behaviour

gtk file dialog window to open

### Screenshots

image
image
image
image

### Attempted Fixes

Attempted many fixes prior to discovering this the XCB and various threading issues that seem to be the root cause of the panics I was originally trying to find. Nothing new attempted with this information

### System Details

```shell
### Build Environment
Wails CLI    | v3.0.0-alpha.4

Go Version   | go1.22.0
Revision     | c1ab0a91fdac1257c74244e45dbcb094d2ad4388
Modified     | true
-buildmode   | exe
-compiler    | gc
CGO_CFLAGS   |
CGO_CPPFLAGS |
CGO_CXXFLAGS |
CGO_ENABLED  | 1
CGO_LDFLAGS  |
GOAMD64      | v1
GOARCH       | amd64
GOOS         | linux
vcs          | git
vcs.modified | true
vcs.revision | c1ab0a91fdac1257c74244e45dbcb094d2ad4388
vcs.time     | 2024-03-24T18:30:19Z

### System
Name         | Ubuntu
Version      | 22.04
ID           | ubuntu
Branding     | 22.04.3 LTS (Jammy Jellyfish)
Platform     | linux
Architecture | amd64
gcc          | 12.9ubuntu3
libgtk-3     | 3.24.33-1ubuntu2
libwebkit    | 2.42.5-0ubuntu0.22.04.2
npm          | 8.5.1~ds-1
pkg-config   | 0.29.2-1ubuntu3
CPU          | AMD Ryzen 7 3700X 8-Core Processor
GPU 1        | Unknown
Memory       | 12GB
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by atterpac**
# Description
(New PR due to unfortunate git circumstances)
Linux file chooser dialogs were having varying errors due to not being called on the main gtk thread. The only change was removing the call to create the dialog from the go routine to handle the response so only the handling of the dialog is done outside of the main thread but the chooser is called correctly.

# TODO
Marked as draft because there is still an issue of selecting a directory it only ever goes into the directory and not selects.

Fixes #3378 

## Type of change

- [ X ] Bug fix (non-breaking change which fixes an issue)
 
# How Has This Been Tested?
- [ X ] Linux
  
## Test Configuration
```
# Build Environment
Wails CLI    | v3.0.0-alpha.4

Go Version   | go1.22.0
Revision     | c1ab0a91fdac1257c74244e45dbcb094d2ad4388
Modified     | true
-buildmode   | exe
-compiler    | gc
CGO_CFLAGS   |
CGO_CPPFLAGS |
CGO_CXXFLAGS |
CGO_ENABLED  | 1
CGO_LDFLAGS  |
GOAMD64      | v1
GOARCH       | amd64
GOOS         | linux
vcs          | git
vcs.modified | true
vcs.revision | c1ab0a91fdac1257c74244e45dbcb094d2ad4388
vcs.time     | 2024-03-24T18:30:19Z

# System
Name         | Ubuntu
Version      | 22.04
ID           | ubuntu
Branding     | 22.04.3 LTS (Jammy Jellyfish)
Platform     | linux
Architecture | amd64
gcc          | 12.9ubuntu3
libgtk-3     | 3.24.33-1ubuntu2
libwebkit    | 2.42.5-0ubuntu0.22.04.2
npm          | 8.5.1~ds-1
pkg-config   | 0.29.2-1ubuntu3
CPU          | AMD Ryzen 7 3700X 8-Core Processor
GPU 1        | Unknown
Memory       | 12GB
```

# Checklist:

- [ ] I have updated `website/src/pages/changelog.mdx` with details of this PR

### CODE REVIEW

**Comment by tmclane** [comment]
Did you not grab the commit I pushed for the directory selection?

**Comment by tmclane** [comment]
oh oops - that isn't correct!  I did push it in to `v3-alpha`.  Ignore my previous statements!

File: v3/pkg/application/linux_cgo.go [hunk 1]
```diff
@@ -1570,11 +1571,12 @@ func runChooserDialog(window pointer, allowMultiple, createFolders, showHidden b
 					}
 					count++
 				}
-				close(selections)
-				C.gtk_widget_destroy((*C.GtkWidget)(unsafe.Pointer(fc)))
+			case C.GTK_RESPONSE_CANCEL:
+				// Cancelled
```
Comment (tmclane) [inline v3/pkg/application/linux_cgo.go:1575]: Honestly I do not see any reason this needed to be switched from an `if statement` to a `switch statement` since the `cancel` case is ignored.  If you wanted it this way for consistency I could see the argument for that, but it appears to simply add extra lines of non-functional code IMHO.

Comment (atterpac) [reply v3/pkg/application/linux_cgo.go:1575]: I was getting errors on my machine if cancel wasn't "handled"

Comment (tmclane) [reply v3/pkg/application/linux_cgo.go:1575]: It's only an error in a `switch` statement.   My point is that if it was still an `if` statement then this wouldn't be an issue.   You could also just add a `default` case to handle that.  I still think this is more code than is necessary in this case since you can only have an `ok` or `not ok`.  Do you have any other changes you are waiting on?

I think I will go ahead and `approve / merge` this otherwise.

**Comment by atterpac** [comment]
Commits should be cleaned up now sorry about that

**Comment by tmclane** [comment]
If you mark this `non-draft` I can approve it.

File: v3/pkg/application/linux_cgo.go (hunk 1 above)
Comment (atterpac) [reply v3/pkg/application/linux_cgo.go]: repushed with swap back to if statement, should be good to ship on my end

File: v3/pkg/application/dialogs_linux.go [hunk 2]
```diff
@@ -28,13 +30,9 @@ func (m *linuxDialog) show() {
...
-	response := runQuestionDialog(pointer(parent), m.dialog)
-	if response >= 0 && response < len(m.dialog.Buttons) {
-		button := m.dialog.Buttons[response]
-		if button.Callback != nil {
-			go button.Callback()
-		}
-	}
+	InvokeAsync(func() {
+		runQuestionDialog(pointer(parent), m.dialog)
+	})
```
Comment (tmclane) [inline v3/pkg/application/dialogs_linux.go:35]: Did you mean to completely remove the `if statement`?

Comment (atterpac) [reply v3/pkg/application/dialogs_linux.go:41]: Accidentally got removed should be fixed

**Review by tmclane — APPROVED** [review]
Let's get this in!
