### PR TITLE
Bugfix/linux warnings

### LINKED ISSUE #1653: [Linux] Gdk-CRITICAL **: 22:17:45.455: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed
### Description

When running an app built with v2.0.0-beta.42 either as a binary or via `wails dev`, when the window opens the following is printed on the console:

```shell
(wailsv2b42:482510): Gdk-CRITICAL **: 22:17:45.455: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed
SetMinMaxSize - min: (0,0) max: (1920,1080)

(wailsv2b42:482510): Gdk-CRITICAL **: 22:17:45.455: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed
SetMinMaxSize - min: (0,0) max: (1920,1080)
SetSize:  1024 768
Center: 489x24
```

Please note that these are not "critical" errors that break anything, just assertions, and there is no need to push out a new release or anything for this. :smile: 

There's some accompanying debug output that should probably go away at some point too.

### To Reproduce

1. Update to wails v2.0.0-beta.42
2. `wails init -t svelte -n wailsv2b42`
3. `cd wailsv2b42`
4. `wails build`
5. `build/bin/wailsv2b42`

### Expected behaviour

Did not expect to see the critical errors (assertions) or debug info.

### Screenshots

_No response_

### Attempted Fixes

_No response_

### System Details

```shell
Wails CLI v2.0.0-beta.42

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             NixOS
Version:        22.11
ID:             nixos
Go Version:     go1.18.4
Platform:       linux
Architecture:   amd64

Wails
------
Version:                v2.0.0-beta.42
Package Manager:        nixpkgs

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
*docker         nixos.docker    Installed       20.10.17
gcc             nixos.gcc       Installed       11.3.0
libgtk-3        nixos.gtk3      Installed       3.24.34
libwebkit       nixos.webkitgtk Installed       2.36.4
npm             nixos.nodejs    Installed       16.15.0
*nsis           nixos.nsis      Available       3.06.1
pkg-config      nixos.pkg-configInstalled       0.29.2
*upx            nixos.upx       Installed       3.96

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - nsis: nix-env -iA nixos.nsis



If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

### Additional context

_No response_

### LINKED ISSUE #1654: [Linux] Gtk-CRITICAL **: 22:23:23.129: gtk_main_quit: assertion 'main_loops != NULL' failed
### Description

When running an app built with Wails v2.0.0-beta.42 (and some earlier versions), whether as a built binary or via `wails dev`, when the app is quit, the following is displayed on the console:

```shell
Gtk-CRITICAL **: 22:23:23.129: gtk_main_quit: assertion 'main_loops != NULL' failed
```

### To Reproduce

1. Update to wails v2.0.0-beta.42
2. `wails init -t svelte -n wailsv2b42`
3. `cd wailsv2b42`
4. `wails build`
5. `build/bin/wailsv2b42`
6. Quit the app.

### Expected behaviour

No critical error displayed on console when app quits.

### Screenshots

_No response_

### Attempted Fixes

_No response_

### System Details

```shell
Wails CLI v2.0.0-beta.42

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             NixOS
Version:        22.11
ID:             nixos
Go Version:     go1.18.4
Platform:       linux
Architecture:   amd64

Wails
------
Version:                v2.0.0-beta.42
Package Manager:        nixpkgs

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
*docker         nixos.docker    Installed       20.10.17
gcc             nixos.gcc       Installed       11.3.0
libgtk-3        nixos.gtk3      Installed       3.24.34
libwebkit       nixos.webkitgtk Installed       2.36.4
npm             nixos.nodejs    Installed       16.15.0
*nsis           nixos.nsis      Available       3.06.1
pkg-config      nixos.pkg-configInstalled       0.29.2
*upx            nixos.upx       Installed       3.96

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - nsis: nix-env -iA nixos.nsis



If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by leaanthony**
Multiple fixes for Linux warnings.
Fixes #1654
Fixes #1653

### CODE REVIEW

**Comment by leaanthony** [comment]
@ianmjones - Please let me know if this fixes the warnings for you 👍

File: v2/internal/frontend/desktop/linux/window.go [hunk 1]
```diff
@@ -63,7 +74,10 @@ static void SetMinMaxSize(GtkWindow* window, int min_width, int min_height, int
     size.min_width = size.min_height = size.max_width = size.max_height = 0;
 
 	GdkRectangle monitorSize = getCurrentMonitorGeometry(window);
-    int flags = GDK_HINT_MAX_SIZE | GDK_HINT_MIN_SIZE;
+	if( isNULLRectangle(monitorSize) ) {
+		return;
```
Comment (stffabi) [inline v2/internal/frontend/desktop/linux/window.go:78]: Just to make sure, do we still apply the constraints for a minimum or maximum in the `options.Options`?

IIRC the call to `SetMinMaxSize` for those is also very early and if the monitorSize couldn't be determined we would skip the constraints.

File: v2/internal/appng/app_production.go [hunk 2]
```diff
@@ -34,15 +34,14 @@ type App struct {
...
-	}
 	a.frontend.Quit()
 }
 
 func (a *App) Run() error {
 	err := a.frontend.Run(a.ctx)
-	a.Shutdown()
+	if a.shutdownCallback != nil {
+		a.shutdownCallback(a.ctx)
+	}
```
[the remark this answers is not in the document]
Comment (leaanthony) [reply v2/internal/appng/app_production.go:44]: Yes! Missed that 😬

File: v2/internal/frontend/desktop/linux/window.go (hunk 1 above)
Comment (leaanthony) [reply v2/internal/frontend/desktop/linux/window.go:78]: I can't confirm tonight but it's interesting it worked at all with a null window. Potentially we'll need to hook on the "present"(?) Signal.

Comment (leaanthony) [reply v2/internal/frontend/desktop/linux/window.go:78]: Looks like the fix may cause issues with fullscreen.

**Review by ianmjones — APPROVED** [review]
This fixed the warnings for me. :tada:

I didn't have any issues using `WindowFullscreen()` from JS either. :shrug:

File: v2/internal/frontend/desktop/linux/window.go (hunk 1 above)
Comment (leaanthony) [reply v2/internal/frontend/desktop/linux/window.go:78]: Can confirm min/max options do not get set on this branch.

**Comment by leaanthony** [comment]
Min/Max size appears to work for me now after merging master.
