### PR TITLE
[v2, darwin] Make sure to copy the uri during processURLRequest

### LINKED ISSUE #1664: [V2] Mac: Inexplicable error log printing
### Description

Sometimes, when I made http request (first request) on golang side, the log will print a error log:
```
ERR | [AssetServer] Error processing request '': Expected host '%!d(string=wails)' in request, but was '' (HttpResponse=500)
```

this log shows only once, what does it mean ?

### To Reproduce

1. run myApp
2. trigger the event of http request on golang side (this log shows only once).
3. can see the error log.
```
### before request
2022/07/27 16:47:51.740048 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'index.html'
2022/07/27 16:47:51.743070 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'assets/index.0a4c8d96.js'
2022/07/27 16:47:51.746641 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'assets/index.a00cf1be.css'
2022/07/27 16:47:52.078224 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'assets/Login.754e322b.css'
2022/07/27 16:47:52.079254 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'assets/Login.d8ef6ce3.js'
2022/07/27 16:47:52.080383 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'assets/App.860583d8.js'
2022/07/27 16:47:52.081206 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'assets/models.0780836a.js'
2022/07/27 16:47:52.109400 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'assets/Login.d8ef6ce3.js'
2022/07/27 16:47:52.111573 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'assets/App.860583d8.js'
2022/07/27 16:47:52.112509 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'assets/models.0780836a.js'

### after request
2022/07/27 16:47:52.917664 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'assets/MainView.d7fb8862.css'
2022/07/27 16:47:52.918236 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'assets/BucketList.31e3f620.css'
2022/07/27 16:47:52.918548 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'assets/MainView.9e55fc6d.js'
2022/07/27 16:47:52.918935 [default_logger.go:78 DEB] [AssetHandler] [AssetHandler] Loading file 'assets/BucketList.25ca96ee.js'
2022/07/27 16:47:52.919262 [default_logger.go:100 ERR] [AssetServer] Error processing request '': Expected host '%!d(string=wails)' in request, but was '' (HttpResponse=500)

```

### Expected behaviour

no error log print

### Screenshots

_No response_

### Attempted Fixes

_No response_

### System Details

```shell
not necessary
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by stffabi**
There's no guarantee that the pointer is still valid when
processURLRequest is finished. So we might end up with an
invalid pointer when the request is asynchronously processed.

Fixes #1664

### CODE REVIEW

File: v2/internal/frontend/desktop/darwin/frontend.go [hunk 1]
```diff
@@ -352,7 +350,9 @@ func (f *Frontend) processRequest(r *request) {
 		headersLen = len(headerData)
 	}
 
-	C.ProcessURLResponse(r.ctx, r.url, C.int(rw.Code), headers, C.int(headersLen), content, C.int(contentLen))
+	url := C.CString(r.url)
+	defer C.free(unsafe.Pointer(url))
```
Comment (leaanthony) [inline v2/internal/frontend/desktop/darwin/frontend.go:354]: Wondering if we should free this in the C function. Should be fine as is as it's the same thread but just wondering...

**Review by leaanthony — APPROVED** [review]

File: v2/internal/frontend/desktop/darwin/frontend.go (hunk 1 above)
Comment (stffabi) [reply v2/internal/frontend/desktop/darwin/frontend.go:354]: From the perspective of responsibilities I would expect the free here, because the memory has been allocated here.

Normally as a callee I would not expect it's needed to free any incoming pointers, because I would expect this is done by the caller which allocated it.
If the data must life beyond the lifetime of a method call, it should be the responsibility of the callee to copy the data or clearly state that the callee takes the ownership of the allocated memory.

Comment (stffabi) [reply v2/internal/frontend/desktop/darwin/frontend.go:354]: The first thing `ProcessURLResponse` does is copy the url into an `NSString` which allows for reference counting on the Objective-C side.
