### PR TITLE
Do not attempt to export fields that cannot be json-encoded

### LINKED ISSUE #3809: models.ts no longer generated after update to v2.9.2
### Description

After updating wails to v2.9.2 (from v2.9.1) models.ts is no longer generated and therefore the frontend fails to build due to typescript errors.
No error is output by typescriptify

### To Reproduce

have menu callbacks defined as app methods (so they can be called from frontend)
reproduction here: https://github.com/BenoitBotton/test

### Expected behaviour

project runs with `wails dev` or builds with `wails build`

### Screenshots

_No response_

### Attempted Fixes

git bisect gives the following:
```
fe1f23b0fd52997b16529a7abb2cfdeb52141601 is the first bad commit
commit fe1f23b0fd52997b16529a7abb2cfdeb52141601
Author: Jeremy Jay <pbnjay@users.noreply.github.com>
Date:   Tue Aug 13 17:49:08 2024 -0400

    If a field is exported, generate json even in the absence of tags (#3678)

    * if no JSON tag, check if field is exported

    * add no-tags binding test case

    * update changelog for #3678

 v2/internal/binding/binding.go                     |  5 +-
 .../binding/binding_test/binding_notags_test.go    | 59 ++++++++++++++++++++++
 v2/internal/binding/binding_test/binding_test.go   |  1 +
 v2/internal/typescriptify/typescriptify.go         |  8 ++-
 website/src/pages/changelog.mdx                    |  1 +
 5 files changed, 72 insertions(+), 2 deletions(-)
 create mode 100644 v2/internal/binding/binding_test/binding_notags_test.go
```

### System Details

```shell
# Wails
Version | v2.9.2

# System
┌─────────────────────────────────────────────────────────────────────────────────────────────────┐
| OS           | Windows 10 Pro                                                                   |
| Version      | 2009 (Build: 22631)                                                              |
| ID           | 23H2                                                                             |
| Go Version   | go1.23.2                                                                         |
| Platform     | windows                                                                          |
| Architecture | amd64                                                                            |
| CPU          | AMD Ryzen 9 5900HX with Radeon Graphics                                          |
| GPU 1        | AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.) - Driver: 31.0.21023.2010 |
| GPU 2        | NVIDIA GeForce RTX 3070 Laptop GPU (NVIDIA) - Driver: 32.0.15.5585               |
| Memory       | 64GB                                                                             |
└─────────────────────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌───────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version       |
| WebView2   | N/A          | Installed | 129.0.2792.79 |
| Nodejs     | N/A          | Installed | 20.10.0       |
| npm        | N/A          | Installed | 10.8.2        |
| *upx       | N/A          | Available |               |
| *nsis      | N/A          | Installed | v3.08         |
└─────────────── * - Optional Dependency ───────────────┘
```

### Additional context

this can obviously be avoided in my project by making the app methods not be menu callbacks, and call them in callback definitions in main.go

### PR DESCRIPTION
**Pull request by pbnjay**
# Description

Some Go types cannot be converted to JSON, and should be excluded from the binding exports. This was an issue when re-using existing Go types (vs types created specifically for Application IPC) when #3678 was introduced.

Fixes #3809 

## Type of change
  
Please select the option that is relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested against the linked repo in issue #3809 and with some local app repos. Added a line to the test case for #3678 so that it will fail prior to this PR.

The scope of the change should not be OS/architecture dependent.
  
## Test Configuration

Please paste the output of `wails doctor`. If you are unable to run this command, please describe your environment in as much detail as possible.

# Checklist:

- [x] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [x] My code follows the general coding style of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved JSON field handling to prevent encoding of unsupported types (channels, functions, complex numbers)
	- Enhanced type serialization logic to skip non-serializable field types
	- Resolved cross-compilation failures related to CGO
	- Fixed issues with `webview2loader` and TypeScript definition for `WindowSetSize`
	- Corrected build failure for non-JSON encodable Go types

- **New Features**
	- Updated changelog with new options for setting window class name on Windows
	- Clarified documentation regarding password syntax and installation requirements for Linux

- **Tests**
	- Updated test struct with a new function field to validate type handling

### CODE REVIEW

File: v2/internal/binding/binding_test/binding_notags_test.go [hunk 1]
```diff
@@ -5,6 +5,7 @@ type NoFieldTags struct {
 	Address string
 	Zip     *string
 	Spouse  *NoFieldTags
+	NoFunc  func() string
```
Comment (leaanthony) [inline v2/internal/binding/binding_test/binding_notags_test.go:8]: Is this needed?

Comment (pbnjay) [reply v2/internal/binding/binding_test/binding_notags_test.go:8]: Before this PR, this line would cause the same problem as the issue in 3809. So if it gets reverted then this will trigger the bug again.

Comment (pbnjay) [reply v2/internal/binding/binding_test/binding_notags_test.go:8]: So not only should it not show up in the test output ~ line 28 of this file, but it would also cause a binding failure.

**Comment by pbnjay** [comment]
Also added UnsafePointer, now all `reflect.Kind` types should be either json-encodable or in the skip list.

**Review by leaanthony — APPROVED** [review]
