### PR TITLE
Devtools hotkey

### LINKED ISSUE #2908: Right click to open inspector does not work when build is generated with -devtools flag only
### Description

Running on latest wails 2.6.0. When build is generated with the devtools only flag, on mac os or windows the right click is still disabled which prevents us from opening inspector.

```
wails build -devtools
```

The -debug flag works as expected and has right click enabled to open inspector.

```
wails build -debug
```

### To Reproduce

1. Create default wails app
2. Run wails build -devtools
3. Start the application and try to open devtools with the right click

### Expected behaviour

Right click working and inspector can be opened from the menu

### Screenshots

_No response_

### Attempted Fixes

_No response_

### System Details

```shell
# Wails
Version | v2.6.0

# System
┌────────────────────────────────────┐
| OS           | Windows 10 Pro      |
| Version      | 2009 (Build: 19045) |
| ID           | 22H2                |
| Go Version   | go1.20              |
| Platform     | windows             |
| Architecture | amd64               |
└────────────────────────────────────┘

# Dependencies
┌───────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version       |
| WebView2   | N/A          | Installed | 114.0.1823.82 |
| Nodejs     | N/A          | Installed | 18.14.2       |
| npm        | N/A          | Installed | 9.5.0         |
| *upx       | N/A          | Available |               |
| *nsis      | N/A          | Available |               |
└─────────────── * - Optional Dependency ───────────────┘

# Diagnosis
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 SUCCESS  Your system is ready for Wails development!
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by leaanthony**
# Description

This PR adds an F12 hotkey shortcut to open the devtools window, whenever the app is built with the `devtools` flag.
Not sure if this could be an issue for signed apps... I don't think it is...

Fixes #2908 

## Type of change
  
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
  
Create a new project, build with `wails build` and check F12 does nothing. Build with `wails build -devtools` and press F12.

- [x] Windows
- [x] macOS
- [x] Linux
  
# Checklist:

- [x] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [x] My code follows the general coding style of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mmghv** [comment]
Works as expected on windows.

Now that F12 opens the devtools, maybe `-devtools` shouldn't enable the default contextmenu? so only `EnableDefaultContextMenu` option enables it in production.

**Comment by leaanthony** [comment]
I'm open to discussion on this. The only edge case is Mac apps that want it enabled and want it on the appstore (does that combo even make sense???).

**Comment by mmghv** [comment]
Can't speak for Mac devs, but if I understand correctly there's no way around it if you want F12 or a runtime method to open it.

Honestly F12 makes a lot of sense and makes life easier, it also solves the default contextmenu problem because now you don't have to show it with `-devtools`.

**Review by stffabi — APPROVED** [review]
LGTM, should we also warn in build.go that private APIs are being used on macOS when build-tag `devtools` is used?

https://github.com/wailsapp/wails/blob/3116c1a62240f4b3441c697e945fd0355c3f2bb4/v2/pkg/commands/build/build.go#L351-L353

**Comment by leaanthony** [comment]
I've changed the key combination to `CTRL/CMD+SHIFT+F12` to make it less likely to clash with current bindings.

**Comment by leaanthony** [comment]
@mmghv - I've removed what I think is the right code to stop `devtools` enabling the default context menu. It looks like it was only enabled in Windows?

**Comment by mmghv** [comment]
> I've removed what I think is the right code to stop devtools enabling the default context menu. It looks like it was only enabled in Windows?

No it exists in all platforms but each with it's own way, also what you changed disabled the default context-menu on windows in `debug` & `dev`, revert it and I'll do it along with some relevant docs changes in a separate PR after you merge this.

File: v2/internal/frontend/desktop/windows/frontend.go [hunk 1]
```diff
@@ -499,7 +511,7 @@ func (f *Frontend) setupChromium() {
 	if err != nil {
 		log.Fatal(err)
 	}
-	err = settings.PutAreDefaultContextMenusEnabled(f.devtools || f.frontendOptions.EnableDefaultContextMenu)
+	err = settings.PutAreDefaultContextMenusEnabled(f.frontendOptions.EnableDefaultContextMenu)
```
Comment (mmghv) [inline v2/internal/frontend/desktop/windows/frontend.go:514]: This change disables the default context-menu on windows in dev & debug because  `f.devtools` is enabled for `-devtools`, `-debug` and dev mode.

**Review by mmghv — CHANGES_REQUESTED** [review]

**Comment by leaanthony** [comment]
Will do tomorrow 👍

**Comment by leaanthony** [comment]
@mmghv - change reverted 👍
