### PR TITLE
[V3] Fix initially-hidden menuItem [mac/win]

### LINKED ISSUE #4088: [v3] Cannot unhide a menu item if it starts hidden
### Description

After the fix for https://github.com/wailsapp/wails/issues/4077, it's not possible to to unhide (show) a menu item that starts off as hidden.  

### To Reproduce

In the `menu` example, add this:

```golang
	// Hidden menu item
	hidden := myMenu.Add("Hidden").SetHidden(true)

	// Unhide callback
	myMenu.Add("Toggle hidden").OnClick(func(ctx *application.Context) {
		hidden.SetHidden(!hidden.Hidden())
	})
```

Then start the example, and click the `Toggle hidden` menu item.  The "Hidden" menu item is not shown (bug).

If you remove the `.SetHidden(true)` from `hidden`, then toggling works correctly, both hiding and unhiding.

### Expected behaviour

I should be able to unhide a menu item that starts off hidden.

### Screenshots

_No response_

### Attempted Fixes

_No response_

### System Details

```shell
# System

┌──────────────────────────────────────────────────┐
| Name          | MacOS                            |
| Version       | 15.2                             |
| ID            | 24C101                           |
| Branding      | Sequoia                          |
| Platform      | darwin                           |
| Architecture  | arm64                            |
| Apple Silicon | true                             |
| CPU           | Apple M2 Max                     |
| CPU 1         | Apple M2 Max                     |
| CPU 2         | Apple M2 Max                     |
| GPU           | 30 cores, Metal Support: Metal 3 |
| Memory        | 64 GB                            |
└──────────────────────────────────────────────────┘

# Build Environment

┌─────────────────────────────────────────────────────────┐
| Wails CLI    | v3.0.0-dev                               |
| Go Version   | go1.24.0                                 |
| Revision     | 5059adc561a9613f943bb9bb1e17d55c83717631 |
| Modified     | false                                    |
| -buildmode   | exe                                      |
| -compiler    | gc                                       |
| CGO_CFLAGS   |                                          |
| CGO_CPPFLAGS |                                          |
| CGO_CXXFLAGS |                                          |
| CGO_ENABLED  | 1                                        |
| CGO_LDFLAGS  |                                          |
| GOARCH       | arm64                                    |
| GOARM64      | v8.0                                     |
| GOOS         | darwin                                   |
| vcs          | git                                      |
| vcs.modified | false                                    |
| vcs.revision | 5059adc561a9613f943bb9bb1e17d55c83717631 |
| vcs.time     | 2025-02-16T05:02:25Z                     |
└─────────────────────────────────────────────────────────┘

# Dependencies

┌───────────────────────────┐
| Xcode cli tools | 2409    |
| npm             | 10.9.2  |
| *NSIS           | v3.10   |
|                           |
└─ * - Optional Dependency ─┘

# Checking for issues

 SUCCESS  No issues found

# Diagnosis

 SUCCESS  Your system is ready for Wails development!
```

### Additional context

Discord thread: https://discord.com/channels/1042734330029547630/1334926670070677555/1334926670070677555

### PR DESCRIPTION
**Pull request by IanVS**
# Description

Fixes #4088

This addresses the referenced issue, allowing menu items to be hidden at first, and then shown in response to some other event.

This also fixes a bug on Windows, which caused duplicate menu items to be added when calling `.SetHidden(false)` on a menu item that was not hidden.

## Type of change
  
Please select the option that is relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
  
I tested this by updating the `menu` example and checking that I can toggle the visibility of the menu item.

I tried in windows, but was not able to figure it out.  I thought maybe removing the `continue` in the similar `processMenu` would have an effect, but it did not.  In fact commenting out the entire `processMenu` function body seemed to have no effect.  I don't know what's going on there.

- [ ] Windows
- [X] macOS
- [ ] Linux
      
If you checked Linux, please specify the distro and version.
  
## Test Configuration

Please paste the output of `wails doctor`. If you are unable to run this command, please describe your environment in as much detail as possible.

# Checklist:

- [ ] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [X] My code follows the general coding style of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
  - Introduced a hidden menu item labeled "I was hidden" in the Demo submenu, which remains concealed by default.
  - Added a toggle option to show or hide the hidden menu item, enhancing interactivity.
  - Improved menu behavior across platforms for a more consistent user experience.
  - Added functionality to set menus dynamically for different operating systems (macOS, Windows, Linux).

- **Bug Fixes**
  - Fixed issues with initially-hidden menu items to ensure they are displayed correctly.

- **Documentation**
  - Added a new section detailing how to set the application menu across various platforms.

### CODE REVIEW

File: v3/pkg/application/popupmenu_windows.go [hunk 1]
```diff
@@ -131,6 +132,12 @@ func (p *Win32Menu) buildMenu(parentMenu w32.HMENU, inputMenu *Menu) {
 				}
 			}
 		}
+
+		// If the item is hidden, don't append
+		if item.Hidden() {
+			continue
```
Comment (IanVS) [inline v3/pkg/application/popupmenu_windows.go:138]: Do we still need to set the menu icon in this case?

File: v3/pkg/application/menu_windows.go [hunk 2]
```diff
@@ -36,6 +36,14 @@ func (w *windowsMenu) update() {
 
 func (w *windowsMenu) processMenu(parentMenu w32.HMENU, inputMenu *Menu) {
 	for _, item := range inputMenu.items {
+		w.currentMenuID++
+		itemID := w.currentMenuID
+		w.menuMapping[itemID] = item
+
+		menuItemImpl := newMenuItemImpl(item, parentMenu, itemID)
```
Comment (IanVS) [inline v3/pkg/application/menu_windows.go:43]: `newMenuItemImpl` was not called previously in this method.

File: v3/pkg/application/popupmenu_windows.go (hunk 1 above)
Comment (leaanthony) [reply v3/pkg/application/popupmenu_windows.go:138]: No I don't think so

**Review by leaanthony — APPROVED** [review]

**Review by leaanthony — APPROVED** [review]
