### PR TITLE
Fix miscellaneous bindings and typescript export bugs

### LINKED ISSUE #2303: A lot of different bugs while generating bindings
### Description

The binding generator does not properly handle maps, type aliases and other packages types:

In my codebase I have a file where I save all the types used in the cross comunications so my binded methods often uses external packages types.
This are some of the types inside intypes.go
```go
type Library struct {
	Comics  ComicsMap `json:"Comics"`
	Version string `json:"Version"`
}
type ComicsMap map[string]Comic
type Comic struct{
	Title string `json:"Title"`
	Slug string `json:"Slug"`
}
```
And this is the method I want to bind inside app.go
```go
func (a *App) GetLibrary() map[string]intypes.Comics {
	\\ my code
}
```
If I try to generate the file I get a non existent and wrong type:
```ts
export function GetLibrary():Promise<map[string]intypes.Comic>;
```

### To Reproduce

1) Define a struct in a separated package
2) Bind a method that returns a map which the value is a type of another package
3) Generate bindings with either wails dev or wails generate module

### Expected behaviour

Generate the bound methods with the proper return type
```ts
export function GetLibrary():Promise<{[key: string]: intypes.Comic}>;
```

### Screenshots

_No response_

### Attempted Fixes

While trying to solve this problem I discovered even more problems.

If I try to return the type alias ComicsMap Like this:
```go
func (a *App) GetLibrary() intypes.ComicsMap {
	\\ my code
}
```

It generate it likes this:
```ts
export function GetLibrary():Promise<intypes.ComicsMap>;
```
Which is correct but it break the import like this:
```ts
import {map[string]intypes} from '../models';
```
and the generated models.ts doesn't have the ComicsMap type inside the intypes namespace.

After this I then tried to create a similar type inside the app.go file (so it simply was map[string]Comic) and did everything as expected confirming that the problem was the different package.
This of course did not solve the problem so I tried returning the Library struct above directly and it worked as expected.

So basically no type aliases, no external packages maps. Bound methods can't return an external package struct if not inside a given struct

### System Details

```shell
# System

OS           | Windows 10 Pro
Version      | 2009 (Build: 19044)
ID           | 21H2
Go Version   | go1.19.4
Platform     | windows
Architecture | amd64

# Wails

Version | v2.3.1

# Dependencies

Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 108.0.1462.76
npm        | N/A          | Installed | 8.15.0
*upx       | N/A          | Available |
*nsis      | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/
```

### Additional context

Aside from the bug I would also advise the use of js Maps:
```ts
export function GetLibrary():Promise<Map<string, intypes.Comic>>;
```
and the creation of types aliases inside the models.ts (if not generating it was intended).

I tried giving a fast look at "internal/binding/generate.go" but I would need more time to figure it out

### LINKED ISSUE #2323: Typescript generation of Generic Struct
### Description

When using a generic struct as a return type of a public function, it generates invalid typescript

### To Reproduce

Go
```go
type Collection[T interface{}] struct {
	Data []T `json:"data"`
}

type Item struct {
	Id int `json:"id"`
}

func (a *App) GetTestData() Collection[Item] {

	var result Collection[Item]

	return result
}

# OR

type ItemCollection = Collection[Item]

func (a *App) GetTestData() ItemCollection {

	var result ItemCollection

	return result
}
```

model.ts
```typescript
	export class Collection[changeme/backend.Item] {
	    data: Item[];
	
	    static createFrom(source: any = {}) {
	        return new Collection[changeme/backend.Item](source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.data = this.convertValues(source["data"], Item);
	    }
	
		convertValues(a: any, classs: any, asMap: boolean = false): any {
		    if (!a) {
		        return a;
		    }
		    if (a.slice) {
		        return (a as any[]).map(elem => this.convertValues(elem, classs));
		    } else if ("object" === typeof a) {
		        if (asMap) {
		            for (const key of Object.keys(a)) {
		                a[key] = new classs(a[key]);
		            }
		            return a;
		        }
		        return new classs(a);
		    }
		    return a;
		}
	}
```

### Expected behaviour

It should generate a new generic type and use that instead

### Screenshots

_No response_

### Attempted Fixes

The only way to get around it is to return `interface{}` or something else that doesn't require generics.

I tried this package and it was able to successfully generate the generics. Could possibly utilise that. `github.com/gzuidhof/tygo` 

### System Details

```shell
Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | MacOS   
Version      | 12.3    
ID           | 21E230  
Go Version   | go1.19.5
Platform     | darwin  
Architecture | arm64   

# Wails

Version | v2.3.1

# Dependencies

Dependency                | Package Name | Status    | Version
Xcode command line tools  | N/A          | Installed | 2395   
npm                       | N/A          | Installed | 8.12.1 
*Xcode                    | N/A          | Available |        
*upx                      | N/A          | Available |        
*nsis                     | N/A          | Available |        
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
```

### Additional context

_No response_

### LINKED ISSUE #2551: Binding has no exported member despite already generated (the binding is not refreshed)
### Description

When I make a function binding to see what I can do with this framework, I got an error that tells me the binding I made has no exported member despite presents on the wailsjs/go/main/App. This behavior only presents in dev mode
I tried to read a file from the backend and then send it to frontend, using this 
```go
package setting

type Setting struct {
	Themes Themes
}

func New() Setting {
	return Setting{
		Themes: Theme(),
	}
}
```
```go
package setting

import (
	"encoding/json"
	"io"
	"log"
	"os"
)

const DEFAULT_THEME_PATH = "/home/thoriqadillah/Development/Go/gown/frontend/theme/default.json"

type Themes struct {
	Components
}

func theme(path string) Components {
	f, err := os.Open(path)
	if err != nil {
		log.Panicf("Error when opening file: %v\n", err)
	}

	data, err := io.ReadAll(f)
	if err != nil {
		log.Panicf("Error when reading file: %v\n", err)
	}

	var components Components
	if err := json.Unmarshal(data, &components); err != nil {
		log.Panicf("Error when reading file: %v\n", err)
	}

	return components
}

func Theme() Themes {
	return Themes{
		Components: theme(DEFAULT_THEME_PATH),
	}
}

type Components struct {
	TextColor       string `json:"textColor"`
	BackgroundColor string `json:"backgroundColor"`
}

```
after that, I'm assigning the struct on the app struct like this
```go
package main

import (
	"changeme/backend/setting"
	"context"
	"fmt"
)

// App struct
type App struct {
	ctx     context.Context
	Setting setting.Setting
}

// NewApp creates a new App application struct
func NewApp() *App {
	return &App{
		Setting: setting.New(),
	}
}

func (a *App) Theme() setting.Themes {
	return a.Setting.Themes
}

```

after that, it generates the following on wailsjs
```ts
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {setting} from '../models';

export function Greet(arg1:string):Promise<string>;

export function Theme():Promise<setting.Themes>;

```

but when I start to import it, it says Module  "../../wailsjs/go/main/App" has no exported member 'Theme"

### To Reproduce

1. Create struct outside main package
2. Add the struct as property in app struct
3. Add function for binding
4. Import the function from frontend
5. You'll see the error

### Expected behaviour

The function can be imported without error

### Screenshots

Screenshot_20230402_123028

### Attempted Fixes

I have tried make the project from new but the problem remains

### System Details

```shell
Wails CLI v2.4.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | Fedora Linux
Version      | 37          
ID           | fedora      
Go Version   | go1.19.6    
Platform     | linux       
Architecture | amd64       

# Wails

Version         | v2.4.1
Package Manager | dnf   

# Dependencies

Dependency | Package Name        | Status    | Version
*docker    | Unknown             | Not Found |        
gcc        | gcc-c++             | Installed | 12.2.1 
libgtk-3   | gtk3-devel          | Installed | 3.24.37
libwebkit  | webkit2gtk4.0-devel | Installed | 2.40.0 
npm        | npm                 | Installed | 9.3.1  
pkg-config | pkgconf-pkg-config  | Installed | 1.8.0  
*upx       | upx                 | Installed | 4.0.2  
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

### Additional context

_No response_

### LINKED ISSUE #2602: Incorrect export class generation for typescript from golang struct
### Description

This issue happens with versions 2.3.1 and 2.4.1
I have a project with Typescript + Wails.

The generated code in models.ts fails to build when adding json tags to a struct in which one of the Items is of type []time.Time

### To Reproduce

1. Add a struct with json tags to a project like the following:
```
import "time"

type Options struct {
	CalendarStartupDates		[]time.Time		`json:"CalendarStartupDates"`
	StartupTime			time.Time		`json:"StartupTime"`
	TimedShutdownTime		time.Time		`json:"TimedShutdownTime"`
}
```
2. Build the project. The frontend will fail to compile. The generated class for this struct in Typescript is:
```
	export class Options {
	    CalendarStartupDates: time.Time[];
	    // Go type: time
	    StartupTime: any;
	    // Go type: time
	    TimedShutdownTime: any;
	//...
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.CalendarStartupDates = this.convertValues(source["CalendarStartupDates"], time.Time);
	        this.StartupTime = this.convertValues(source["StartupTime"], null);
	        this.TimedShutdownTime = this.convertValues(source["TimedShutdownTime"], null);
	    }
	//...
	}
```

### Expected behaviour

I assume that the generated type for `CalendarStartupDates` should be `any[]` instead of `time.Time[]`.

### Screenshots

_No response_

### Attempted Fixes

Removing the json tags from the struct stops the build from failing. 
I have a custom interface for this data in my code so I don't really need it, but there doesn't seem to be any other way to stop this from being generated.

### System Details

```shell
# System

OS           | Windows 10 Home
Version      | 2009 (Build: 22621)
ID           | 22H2
Go Version   | go1.20
Platform     | windows
Architecture | amd64

# Wails

Version | v2.4.1

# Dependencies

Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 112.0.1722.39
npm        | N/A          | Installed | 8.15.0
*upx       | N/A          | Available |
*nsis      | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
```

### Additional context

I stumbled upon this problem because I need the json tags in Go so that I can export data in json format to a file.

Also on a side note, wails doctor reports the OS is windows 10, when it's actually windows 11.

### LINKED ISSUE #3371: Issues with generating App.d.ts and model.ts files for structs that use generic types.
### Description

When attempting to return a struct that has a generic type, the App.d.ts file is incorrectly generated and contains typos.
It is very close, but it doesn't finish out the line.

It also generates an invalid models.ts file.

I've seen similar issues with #2323 and #2303, but neither seemed to have identical problems here.

### To Reproduce

I created a "dbConnection.go" file in the main package and created the following structs.
```go
type Database interface {
	Initialize() error
	Disconnect() error
}

type UserPermissionResult struct {
	Name           string  `json:"Name"`
	PermissionName string  `json:"PermissionName"`
	ObjectName     *string `json:"ObjectName"`
}

type DataResult interface {
	UserPermissionResult
}

type QueryResult[T DataResult] struct {
	Duration time.Duration `json:"Duration"`
	Data     []T           `json:"Data"`
}
```
I then attempt to return QueryResult from a function.

```go
func (a *App) GetUserPermissions(databaseKey string, user string, target string) (QueryResult[UserPermissionResult], error) {}
```

The resulting "App.d.ts" file looks like this.

```ts
import {main} from '../models';

export function GetUserPermissions(arg1:string,arg2:string,arg3:string):Promise<main.QueryResult[main>;
```

It is very close but as you can see there is a typo in the Promise return type. To manually fix it, you just have to change it to the following manually

```ts
import {main} from '../models';

export function GetUserPermissions(arg1:string,arg2:string,arg3:string):Promise<main.QueryResult[main.UserPermissionResult]>;
```

As for "models.ts" the resulting file looks like this.

```ts
export namespace main {
	export class UserPermissionResult {
	    Name: string;
	    PermissionName: string;
	    ObjectName?: string;
	
	    static createFrom(source: any = {}) {
	        return new UserPermissionResult(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.Name = source["Name"];
	        this.PermissionName = source["PermissionName"];
	        this.ObjectName = source["ObjectName"];
	    }
	}
	export class QueryResult[main.UserPermissionResult] {
	    Duration: number;
	    Data: UserPermissionResult[];
	
	    static createFrom(source: any = {}) {
	        return new QueryResult[main.UserPermissionResult](source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.Duration = source["Duration"];
	        this.Data = this.convertValues(source["Data"], UserPermissionResult);
	    }
	
		convertValues(a: any, classs: any, asMap: boolean = false): any {
		    if (!a) {
		        return a;
		    }
		    if (a.slice) {
		        return (a as any[]).map(elem => this.convertValues(elem, classs));
		    } else if ("object" === typeof a) {
		        if (asMap) {
		            for (const key of Object.keys(a)) {
		                a[key] = new classs(a[key]);
		            }
		            return a;
		        }
		        return new classs(a);
		    }
		    return a;
		}
	}
}
```
This is a bit of a mixed bag, and I don't know how to fix it.
You'll see that first it's defining the class incorrectly. 
It needs <> instead of [] for the generics. It's also using a concrete type for the class. 
If we change `export class QueryResult[main.UserPermissionResult]` to `export class QueryResult<T>` then there are issues down the line with `convertValues`. You can't pass T as a type for `classs`.

I'm not sure how this would be fixed as I'm no TS expert.

### Expected behaviour

The models.ts file should generate a proper class that uses generic types.
App.d.ts should finish the type declaration in the promise.

### Screenshots

![image](https://github.com/wailsapp/wails/assets/56038965/b0494bed-824e-4542-b889-7ad710addb27)
![image](https://github.com/wailsapp/wails/assets/56038965/33501e24-dbfe-4024-812b-434bc94c9903)


### Attempted Fixes

For the time being, I'm going to change the return type to string and serialize the result then deserialize it on the JS side.
I've tried manually changing the generated file but was unable to find a fix due to the `convertValues` function unable to take a generic type.

### System Details

```shell
Wails Doctor          
                                

                                                                                                                                                                                                                                                                     
# Wails
Version         | v2.8.0
Package Manager | apt   

# System
┌──────────────────────────────────────────────────────────┐
| OS           | Ubuntu                                    |
| Version      | 22.04                                     |
| ID           | ubuntu                                    |
| Go Version   | go1.22.0                                  |
| Platform     | linux                                     |
| Architecture | amd64                                     |
| CPU 1        | Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz |
| CPU 2        | Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz |
| GPU          | SVGA II Adapter (VMware) - Driver: vmwgfx |
| Memory       | 8GB                                       |
└──────────────────────────────────────────────────────────┘

# Dependencies
┌──────────────────────────────────────────────────────────────────────────┐
| Dependency | Package Name          | Status    | Version                 |
| *docker    | docker.io             | Installed | 26.0.0                  |
| gcc        | build-essential       | Installed | 12.9ubuntu3             |
| libgtk-3   | libgtk-3-dev          | Installed | 3.24.33-1ubuntu2        |
| libwebkit  | libwebkit2gtk-4.0-dev | Installed | 2.42.5-0ubuntu0.22.04.2 |
| npm        | npm                   | Installed | 10.2.4                  |
| *nsis      | nsis                  | Available | 3.08-2                  |
| pkg-config | pkg-config            | Installed | 0.29.2-1ubuntu3         |
└──────────────────────── * - Optional Dependency ─────────────────────────┘

# Diagnosis
Optional package(s) installation details: 
  - nsis: sudo apt install nsis
```


### Additional context

_No response_

### LINKED ISSUE #3442: Slice of array causes `wails generate module` to fail
### Description

`wails generate module` fails when a slice of array is part of an exported struct.

This bug could be related to #2323, #2303 too.

### To Reproduce

1. `wails init -n test-bug`
2. `cd test-bug`
3. `go get github.com/google/uuid`
4. Add the following lines to `app.go` and add `"github.com/google/uuid"` to the imports

```golang
/* Copy the following code to your app.go file */
/* Add "github.com/google/uuid" to the imports */

type Works struct {
	Bytes   [1]byte   `json:"bytes" validate:""`
	Strings [1]string `json:"strings" validate:""`
	UUID    uuid.UUID `json:"uuid" validate:""`
}

type DoesNotWork struct {
	Bytes   [][1]byte   `json:"bytes" validate:""`
	Strings [][1]string `json:"strings" validate:""`
	UUIDs   []uuid.UUID `json:"uuids" validate:""`
}

// modules are generated
func (a *App) Works() Works {
	return Works{}
}

// modules are not generated
func (a *App) DoesNotWork() DoesNotWork {
	return DoesNotWork{}
}
```

5. `go mod tidy`
6. `wails generate module` 

The following are obtained by having only one of `DoesNotWork` struct fields at the time.

**DoesNotWork.Bytes**
```
2024/04/28 14:15:04 Error: cannot find type for array (bytes/)
```

**DoesNotWork.Strings**
```
2024/04/28 14:15:46 Error: cannot find type for array (strings/)
```

**DoesNotWork.UUIDs**
```
2024/04/28 14:16:21 Error: cannot find type for array (uuids/UUID)
```


### Expected behaviour

modules are generated

### Screenshots

_No response_

### Attempted Fixes

_No response_

### System Details

```shell
Wails Doctor          
                                

                                                                                                                                                                                                                                                   
# Wails
Version | v2.8.1

# System
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| OS           | MacOS                                                                                                                       |
| Version      | 14.4.1                                                                                                                      |
| ID           | 23E224                                                                                                                      |
| Go Version   | go1.22.0                                                                                                                    |
| Platform     | darwin                                                                                                                      |
| Architecture | arm64                                                                                                                       |
| CPU          | Apple M2 Max                                                                                                                |
| GPU          | Chipset Model: Apple M2 Max Type: GPU Bus: Built-In Total Number of Cores: 30 Vendor: Apple (0x106b) Metal Support: Metal 3 |
| Memory       | 32GB                                                                                                                        |
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌───────────────────────────────────────────────────────────────────────┐
| Dependency                | Package Name | Status    | Version        |
| Xcode command line tools  | N/A          | Installed | 2406           |
| Nodejs                    | N/A          | Installed | 21.6.1         |
| npm                       | N/A          | Installed | 10.2.4         |
| *Xcode                    | N/A          | Installed | 15.3 (15E204a) |
| *upx                      | N/A          | Available |                |
| *nsis                     | N/A          | Available |                |
└─────────────────────── * - Optional Dependency ───────────────────────┘

# Diagnosis
Optional package(s) installation details: 
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 SUCCESS  Your system is ready for Wails development!

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```


### Additional context

Discovered while migrating UUIDs in a personal project from string to uuid.UUID.

### LINKED ISSUE #3709: Loss of models Scope When Using map[string]*models.XX convert to go/models.ts
### Description

map type cant with pointer value

### To Reproduce

with pointer
```go
type Config struct {
	baseDir       string
	SystemConfig  *models.SystemConfig            `json:"system"`  
	PluginConfigs map[string]*models.PluginConfig `json:"plugins"` // here
	Test          *models.SystemConfig            `json:"test"`
}
```
convert to
```typescript
export namespace config {
	
	export class Config {
	    system?: models.SystemConfig;  // works well
	    plugins: {[key: string]: PluginConfig}; // <==here,  error loss models.
	    test?: models.SystemConfig; // works well
```

### Expected behaviour

```typescript
export namespace config {
	
	export class Config {
	    system?: models.SystemConfig;  // works well
	    plugins: {[key: string]: mdels.PluginConfig}; // 
	    test?: models.SystemConfig; // works well
```

### Screenshots

_No response_

### Attempted Fixes

_No response_

### System Details

```shell
┌───────────────────────────────────────────────────────────────────────────┐
| OS           | Windows 10 Pro                                             |
| Version      | 2009 (Build: 19045)                                        |
| ID           | 22H2                                                       |
| Go Version   | go1.22.1                                                   |
| Platform     | windows                                                    |
| Architecture | amd64                                                      |
| CPU          | Intel(R) Core(TM) i7-8700K                  |
| GPU          | NVIDIA GeForce GTX 1660 Ti (NVIDIA) - Driver: 31.0.15.3623 |
| Memory       | 16GB                                                       |
└───────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌────────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version        |
| WebView2   | N/A          | Installed | 127.0.2651.105 |
| Nodejs     | N/A          | Installed | 20.11.0        |
| npm        | N/A          | Installed | 10.3.0         |
| *upx       | N/A          | Installed | upx 4.2.4      |
| *nsis      | N/A          | Available |                |
└─────────────── * - Optional Dependency ────────────────┘
```

### Additional context

_No response_

### LINKED ISSUE #3755: v2.9.2 cannot find type for func (CheckRedirect/)
### Description

After upgrading v2.9.2, when running wails dev, the following error is reported. v2.9.1 is normal.
```
  • Generating bindings: 
          Converting type internal.Response
          - simple field Response.Code
          - simple field Response.Msg
          - simple field Response.Data
          Converting type http.Client
          - simple field Client.Transport
          - simple field Client.CheckRedirect
          2024/09/19 22:38:10 cannot find type for func (CheckRedirect/)
```

### To Reproduce

```
wails dev
func (t *App)  any() *http.Client {
        ...................
	client := &http.Client{
		Transport:     transport,
		Timeout:       10 * time.Second,
		CheckRedirect: http.DefaultClient.CheckRedirect,
	}
	return client
}
```

### Expected behaviour

everything is running normally

### Screenshots

_No response_

### Attempted Fixes

_No response_

### System Details

```shell
Wails Doctor          
                                


# Wails
Version | v2.9.2

# System
┌──────────────────────────────────────────────────────────────────────────────────────────────┐
| OS           | Windows 10 Pro                                                                |
| Version      | 2009 (Build: 22631)                                                           |
| ID           | 23H2                                                                          |
| Go Version   | go1.22.7                                                                      |
| Platform     | windows                                                                       |
| Architecture | amd64                                                                         |
| CPU          | AMD Ryzen 9 7950X 16-Core Processor                                           |
| GPU          | AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.) - Driver: 32.0.11016.3 |
| Memory       | 64GB                                                                          |
└──────────────────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌───────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version       |
| WebView2   | N/A          | Installed | 128.0.2739.79 |
| Nodejs     | N/A          | Installed | 20.17.0       |
| npm        | N/A          | Installed | 10.8.2        |
| *upx       | N/A          | Available |               |
| *nsis      | N/A          | Available |               |
└─────────────── * - Optional Dependency ───────────────┘

# Diagnosis
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 SUCCESS  Your system is ready for Wails development!

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

```
```


### Additional context

_No response_

### LINKED ISSUE #3900: Structural conversion problem
### Description

```
type ListData[T interface{}] struct {
	Total     int64 `json:"Total"`
	TotalPage int64 `json:"TotalPage"`
	PageNum   int   `json:"PageNum"`
	List      T     `json:"List,omitempty"`
}
```
Such a structure is wrong when converted to ts

### To Reproduce

D:\work\gowork\alctserver> wails dev -m                                                                                                                                           2024/11/22 10:57:02Wails CLI v2.9.2

  • Generating bindings: 2024/11/22 10:57:11 KnownStructs: models.ListSearchReq pkg.ListData[[]*alctgo/model    pkg.PageParams  pkg.Res[alctgo/pkg.ListData[[]*alctgo/model.AlctDriverNew]]     pkg.Res[string]
pkg.ListData[alctgo/model.AlctDriverNew]

### Expected behaviour

 wailsjs/go/main/App.d.ts(14,95): error TS1005: ']' expected.
    wailsjs/go/models.ts(20,23): error TS1005: '{' expected.
    wailsjs/go/models.ts(20,55): error TS1005: ';' expected.
    wailsjs/go/models.ts(24,11): error TS1109: Expression expected.
    wailsjs/go/models.ts(24,33): error TS1011: An element access expression should take an argument.
    wailsjs/go/models.ts(26,6): error TS1128: Declaration or statement expected.
    wailsjs/go/models.ts(26,30): error TS1005: ',' expected.
    wailsjs/go/models.ts(26,42): error TS1005: ';' expected.

### Screenshots

_No response_

### Attempted Fixes

_No response_

### System Details

```shell
# Wails
Version | v2.9.2

# System
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| OS           | Windows 10 IoT Enterprise LTSC 2021                                                              |
| Version      | 2009 (Build: 19044)                                                                              |
| ID           | 21H2                                                                                             |
| Go Version   | go1.21.11                                                                                        |
| Platform     | windows                                                                                          |
| Architecture | amd64                                                                                            |
| CPU          | Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz                                                         |
| GPU 1        | OrayIddDriver Device (Shanghai Best Oray Information Technology Co., Ltd.) - Driver: 17.1.58.818 |
| GPU 2        | Intel(R) UHD Graphics 630 (Intel Corporation) - Driver: 31.0.101.2111                            |
| Memory       | 24GB                                                                                             |
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌───────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version       |
| WebView2   | N/A          | Installed | 130.0.2849.80 |
| Nodejs     | N/A          | Installed | 20.15.0       |
| npm        | N/A          | Installed | 10.7.0        |
| *upx       | N/A          | Available |               |
| *nsis      | N/A          | Installed | v3.10         |
└─────────────── * - Optional Dependency ───────────────┘
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pbnjay**
# Description

This is building upon the changes in v2.9.2 and #3678, and on top of PR #3975, to fix a lot of issues around generation in `models.ts`. Mostly this is intended to clear out some of the old issues but also as a stop-gap so that I can start transitioning my own projects to v3 =)

Some of these don't have clear reproduction examples, but I've tried to include examples of these issues in my local testing, I would appreciate some other eyes:

Fixes #3900
Fixes #3709 
Fixes #3371
Sorta fixes #2602 (already fixed via 'any' / KnownStructs, though for time.Time specifically there are no exported fields)
Fixes #2551
Fixes #2303
Fixes #2323
Fixes #3755
Fixes #3442 (from crashing, not full type though)

Given the number of issues, I fully expect some updates to come for these changes! A few of them I'm not sure if they were holdovers from prior work or some edge case I don't know about or what. Happy to learn more and update!

## Type of change
  
Please select the option that is relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Example test suite in a gist: https://gist.github.com/pbnjay/73ef5a944dd12f6f2962f4fe14099912

## Test Configuration

Please paste the output of `wails doctor`. If you are unable to run this command, please describe your environment in as much detail as possible.

# Checklist:

- [x] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [x] My code follows the general coding style of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Release Notes

- **New Features**
	- Added option to set window class name on Windows

- **Fixed**
	- Resolved `models.ts` build failure caused by non-JSON-encodable Go types
	- Fixed cross-compilation issues with CGO
	- Updated native `webview2loader` using `go-webview2` version 0.1.17
	- Corrected TypeScript definition for `WindowSetSize`
	- Resolved flickering issue with frameless windows on Windows
	- Fixed additional binding and TypeScript export bugs

- **Improvements**
	- Enhanced TypeScript type handling and generation
	- Improved JSON serialization robustness
	- Updated type conversion processes to handle generic types more effectively

### CODE REVIEW

File: v2/internal/binding/binding.go [hunk 1]
```diff
@@ -277,7 +277,7 @@ func (b *Bindings) AddStructToGenerateTS(packageName string, structName string,
 				continue
 			}
 			fqname := field.Type.String()
-			sNameSplit := strings.Split(fqname, ".")
+			sNameSplit := strings.SplitN(fqname, ".", 2)
```
Comment (pbnjay) [inline v2/internal/binding/binding.go:280]: line 284 throws away the rest, we want to keep them

File: v2/internal/typescriptify/typescriptify.go [hunk 2]
```diff
@@ -261,15 +275,22 @@ func (t *TypeScriptify) AddType(typeOf reflect.Type) *TypeScriptify {
 func (t *typeScriptClassBuilder) AddMapField(fieldName string, field reflect.StructField) {
 	keyType := field.Type.Key()
 	valueType := field.Type.Elem()
-	valueTypeName := valueType.Name()
+	valueTypeName := nameTypeOf(valueType)
+	if valueType.Kind() == reflect.Ptr {
```
Comment (pbnjay) [inline v2/internal/typescriptify/typescriptify.go:279]: matches Ptr unwrapping everywhere else in this file

without this, a map value that is a pointer to a struct looses its namespace #3709

File: v2/internal/typescriptify/typescriptify.go [hunk 3]
```diff
@@ -261,15 +275,22 @@ func (t *TypeScriptify) AddType(typeOf reflect.Type) *TypeScriptify {
...
 	}
 	if valueType.Kind() == reflect.Array || valueType.Kind() == reflect.Slice {
-		valueTypeName = valueType.Elem().Name() + "[]"
+		valueTypeName = nameTypeOf(valueType.Elem()) + "[]"
 	}
 	if valueType.Kind() == reflect.Ptr {
-		valueTypeName = valueType.Elem().Name()
+		valueTypeName = nameTypeOf(valueType.Elem())
+	}
+	if valueType.Kind() == reflect.Map {
```
Comment (pbnjay) [inline v2/internal/typescriptify/typescriptify.go:291]: previously there was no reflect.Map here, so valueTypeName defaulted to "" and caused invalid typescript with e.g. nested map[string]map[string]string.

any here gives valid code at least, future work to recursively generate?

File: v2/internal/typescriptify/typescriptify.go [hunk 4]
```diff
@@ -659,8 +690,10 @@ func (t *TypeScriptify) convertType(depth int, typeOf reflect.Type, customCode m
 			}
 
 			isKnownType := t.KnownStructs.Contains(getStructFQN(field.Type.String()))
-			println("KnownStructs:", t.KnownStructs.Join("\t"))
-			println(getStructFQN(field.Type.String()))
+			if !isKnownType {
```
Comment (pbnjay) [inline v2/internal/typescriptify/typescriptify.go:693]: This is very loud with a lot of structs. Quieting it unless it misses something

File: v2/internal/typescriptify/typescriptify.go [hunk 5]
```diff
@@ -920,7 +955,7 @@ func indentLines(str string, i int) string {
 
 func getStructFQN(in string) string {
 	result := strings.ReplaceAll(in, "[]", "")
-	result = strings.ReplaceAll(result, "*", "")
+	//result = strings.ReplaceAll(result, "*", "")
```
Comment (pbnjay) [inline v2/internal/typescriptify/typescriptify.go:958]: This is a question mark for me. I believe with the pointer unwrapping it is unnecessary now but it needs to match the same name generation as in binding.go

**Comment by leaanthony** [comment]
Thanks for taking the time to do this. That is indeed a lot of issues fixed 😅 Could you please add tests for the changes so we can be sure they don't break in the future? Many thanks 🙏

**Comment by pbnjay** [comment]
Bugs #3900, #3371, #2323 tested in `binding_generics_test.go`
Bugs #3755, #3809 tested in `binding_ignored_test.go`
Bugs #3709, #3442, #2303 tested in `binding_deepelements_test.go`
Bug #2551 was actually covered by #3678 but since this fixes some issues with that we can close it here.

I have some ideas for #2602 but it may not be worth the effort...

**Comment by leaanthony** [comment]
Thanks 🙏 Please could you add an entry to the changelog located at `website/src/pages/changelog.mdx`?

**Review by leaanthony — APPROVED** [review]

**Comment by leaanthony** [comment]
Thanks for all your time on this 🙏 An amazing contribution to the community!
