### PR TITLE
Fix signal handler

### LINKED ISSUE #2134: fatal error: non-Go code set up signal handler without SA_ONSTACK flag
### Description

First off, I'm not sure if this is a bug in Wails. It could totally be in my own app! However, I'm not using cgo in my code or my go.mod dependencies (edit: except for sqlite, but that's not new -- and I've never seen this before until using Wails).

This is a similar to https://github.com/wailsapp/wails/issues/1570, but I'm not using gRPC at all.

My program was running under `wails dev`, and while I wasn't interacting with it, it crashed:

```
signal 11 received but handler not on signal stack
fatal error: non-Go code set up signal handler without SA_ONSTACK flag

runtime stack:
runtime.throw({0x2330cad?, 0xc00009c000?})
        /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc000763618 sp=0xc0007635e8 pc=0x44dbfd
runtime.sigNotOnStack(0xb)
        /usr/local/go/src/runtime/signal_unix.go:1020 +0x65 fp=0xc000763638 sp=0xc000763618 pc=0x465305
runtime.adjustSignalStack(0xb, 0xc000780000, 0xc?)
        /usr/local/go/src/runtime/signal_unix.go:581 +0x156 fp=0xc000763698 sp=0xc000763638 pc=0x464156
runtime.sigtrampgo(0xb, 0xc0007639b0, 0xc000763880)
        /usr/local/go/src/runtime/signal_unix.go:469 +0x13b fp=0xc000763710 sp=0xc000763698 pc=0x463e3b
runtime.sigtramp()
        /usr/local/go/src/runtime/sys_linux_amd64.s:359 +0x46 fp=0xc000763760 sp=0xc000763710 pc=0x484b46

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000aafe8 sp=0xc0000aafe0 pc=0x482ea1

goroutine 1 [syscall, 7 minutes, locked to thread]:
runtime.cgocall(0x1f2b240, 0xc0006b5b08)
        /usr/local/go/src/runtime/cgocall.go:158 +0x5c fp=0xc0006b5ae0 sp=0xc0006b5aa8 pc=0x41149c
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux._Cfunc_gtk_main()
        _cgo_gotypes.go:1068 +0x45 fp=0xc0006b5b08 sp=0xc0006b5ae0 pc=0xd21f65
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Frontend).RunMainLoop(0xc000b89c80)
        /home/matt/go/pkg/mod/github.com/wailsapp/wails/v2@v2.2.0/internal/frontend/desktop/linux/frontend.go:57 +0x1c fp=0xc0006b5b18 sp=0xc0006b5b08 pc=0xd2499c
github.com/wailsapp/wails/v2/internal/frontend/devserver.(*DevWebServer).RunMainLoop(0xc000187ef0)
        <autogenerated>:1 +0x34 fp=0xc0006b5b30 sp=0xc0006b5b18 pc=0xe03514
github.com/wailsapp/wails/v2/internal/app.(*App).Run(0xc000586780)
        /home/matt/go/pkg/mod/github.com/wailsapp/wails/v2@v2.2.0/internal/app/app_dev.go:30 +0x72 fp=0xc0006b5b98 sp=0xc0006b5b30 pc=0xe0ddf2
github.com/wailsapp/wails/v2/pkg/application.(*Application).Run(0xc00028dbc0)
        /home/matt/go/pkg/mod/github.com/wailsapp/wails/v2@v2.2.0/pkg/application/application.go:69 +0x169 fp=0xc0006b5c10 sp=0xc0006b5b98 pc=0xe10bc9
github.com/wailsapp/wails/v2.Run(0xc000164d80)
        /home/matt/go/pkg/mod/github.com/wailsapp/wails/v2@v2.2.0/wails.go:14 +0x33 fp=0xc0006b5c50 sp=0xc0006b5c10 pc=0xe10d53
.
.
.
```

Full stack trace is 700 lines. Let me know if you want me to provide it.

When this happened, my program did stop, but the CLI command kept running. I had to send it a signal to stop `wails dev`:

```
^C
Caught quit
Development mode exited

If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

### To Reproduce

~~Sadly, I don't know how to reproduce this. It has only happened this one time, and it is not the first time I have run these exact same functions on the exact same inputs. If it happens again I will let you know...~~

UPDATE: Put this right inside `main()`:

```
go func() {
	time.Sleep(5 * time.Second)
	var t *time.Time
	log.Println(t.Unix())
}()
```

### Expected behaviour

Not crash :)

### Screenshots

_No response_

### Attempted Fixes

_No response_

### System Details

```shell
$ wails doctor
Wails CLI v2.2.0

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Pop!_OS
Version:        22.04
ID:             pop
Go Version:     go1.19.1
Platform:       linux
Architecture:   amd64

Wails
------
Version:                v2.2.0
Package Manager:        apt

Dependency      Package Name            Status          Version
----------      ------------            ------          -------
*docker         docker.io               Available       20.10.12-0ubuntu4
gcc             build-essential         Installed       11.3.0
libgtk-3        libgtk-3-dev            Installed       3.24.33-1ubuntu2
libwebkit       libwebkit2gtk-4.0-dev   Installed       2.38.2-0ubuntu0.22.04.2
npm             npm                     Installed       8.5.1~ds-1
*nsis           nsis                    Available       3.08-2
pkg-config      pkg-config              Installed       0.29.2

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - docker: sudo apt install docker.io
  - nsis: sudo apt install nsis



If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

### Additional context

Sorry this isn't the most helpful report. Let me know if you need more info!

### PR DESCRIPTION
**Pull request by leaanthony**
This PR sets up a new signal handler in C that overrides the current one (in C) so that `SA_ONSTACK` is used. When used against the nil dereference example @mholt gave, it appears to work as expected.

Closes #2134

### CODE REVIEW

**Comment by leaanthony** [comment]
@mholt - any chance you could try this against your *original* issue (before you fixed it)?

**Comment by stffabi** [comment]
Good question, I've moved the `gtk_init` to `init()` so that's the only thing I could think of that would interfere. But currently the fixup is also dane after `gtk_init` so I think we should be fine.

File: v2/internal/frontend/desktop/linux/frontend.go [hunk 1]
```diff
@@ -9,6 +9,69 @@ package linux
...
+#include <string.h>
+
+static void fix_signal(int signum)
+{
+    struct sigaction st;
+
+    if (sigaction(signum, NULL, &st) < 0) {
+        goto fix_signal_error;
+    }
+    st.sa_flags |= SA_ONSTACK;
```
Comment (stffabi) [inline v2/internal/frontend/desktop/linux/frontend.go:25]: Should we skip fixup the signal handler if the `SA_ONSTACK` flag is already set?

**Review by stffabi — APPROVED** [review]
LGTM 🚀 , just added a minor comment.

File: v2/internal/frontend/desktop/linux/frontend.go (hunk 1 above)
Comment (stffabi) [reply v2/internal/frontend/desktop/linux/frontend.go:25]: Yeah absolutely, would maybe just save some cycles for internal setting up the handler in the kernel when it's already fine.But that can be neglected 😄

**Comment by mholt** [comment]
@leaanthony I will try this out ASAP! Is it OK if I run with `-skipbindings` for now? (See Slack for the error I'm getting about `-tsprefix` otherwise)

**Comment by YOU54F** [comment]
Thanks for this fix @leaanthony - This was helpful for me in solving a pesky bug in pact-go where we consume a rust shared library, in various languages including golang via cgo.

The issue only crops up where the rust shared library calls out to external plugins and manages their process lifecycle.

https://github.com/pact-foundation/pact-go/issues/269

**Comment by leaanthony** [comment]
I'm glad it was useful 🙏
