### PR TITLE
wails3 alpha windows: fix crash when systray icon is clicked without an attached window

### LINKED ISSUE #3270: Wails3 alpha: Left clicking the systray crashes the app when systray is in flyout  (Windows)
### Description

When the systray icon is hidden in the flyout thingy on windows and the systray doesn't have a window attached, the application crashes if you left click the app.

```go```

callstack:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x9586f4]

goroutine 1 [running, locked to thread]:
github.com/wailsapp/wails/v3/pkg/application.(*windowsSystemTray).openMenu(0xc0001d4340)
        C:/Users/calle/source/wails/v3/pkg/application/systemtray_windows.go:44 +0x34
github.com/wailsapp/wails/v3/pkg/application.InvokeSync.func1()
        C:/Users/calle/source/wails/v3/pkg/application/mainthread.go:28 +0x42
github.com/wailsapp/wails/v3/pkg/application.(*App).dispatchOnMainThread(0xc0000f3348, 0xc000126240)        
        C:/Users/calle/source/wails/v3/pkg/application/application.go:743 +0xcb
github.com/wailsapp/wails/v3/pkg/application.InvokeSync(0xc000126228)
        C:/Users/calle/source/wails/v3/pkg/application/mainthread.go:26 +0x94
github.com/wailsapp/wails/v3/pkg/application.(*SystemTray).OpenMenu(...)
        C:/Users/calle/source/wails/v3/pkg/application/systemtray.go:298
github.com/wailsapp/wails/v3/pkg/application.(*SystemTray).defaultClickHandler(0xc0000b6601?)
        C:/Users/calle/source/wails/v3/pkg/application/systemtray.go:269 +0x156
github.com/wailsapp/wails/v3/pkg/application.(*windowsSystemTray).wndProc(0xc0001d4340, 0x401, 0x3050498, 0x10202)
        C:/Users/calle/source/wails/v3/pkg/application/systemtray_windows.go:281 +0x6e
github.com/wailsapp/wails/v3/pkg/application.(*windowsApp).wndProc(0xc0002280e0, 0xe0584, 0x401, 0x3050498, 0x10202)
        C:/Users/calle/source/wails/v3/pkg/application/application_windows.go:281 +0x4fe
syscall.SyscallN(0x1c44fc61348?, {0xc000480000?, 0x0?, 0xc000480000?})
        C:/Program Files/Go/src/runtime/syscall_windows.go:544 +0x107
syscall.(*Proc).Call(0x472385?, {0xc000480000?, 0x9bccc0?, 0x2701?})
        C:/Program Files/Go/src/syscall/dll_windows.go:166 +0x1c
syscall.(*LazyProc).Call(0xf9eae0, {0xc000480000, 0x4, 0x4})
        C:/Program Files/Go/src/syscall/dll_windows.go:286 +0x4a
github.com/wailsapp/wails/v3/pkg/w32.GetMessage(...)
        C:/Users/calle/source/wails/v3/pkg/w32/user32.go:423
github.com/wailsapp/wails/v3/pkg/application.(*windowsApp).runMainLoop(0xc0002280e0)
        C:/Users/calle/source/wails/v3/pkg/application/mainthread_windows.go:62 +0x174
github.com/wailsapp/wails/v3/pkg/application.(*windowsApp).run(0xc0002280e0)
        C:/Users/calle/source/wails/v3/pkg/application/application_windows.go:189 +0xd2
github.com/wailsapp/wails/v3/pkg/application.(*App).Run(0xc0000f3348)
        C:/Users/calle/source/wails/v3/pkg/application/application.go:537 +0x3d3
main.main()
        C:/Users/calle/source/wails/v3/examples/systray/main.go:66 +0x516
[0221/195318.555:ERROR:window_impl.cc(120)] Failed to unregister class Chrome_WidgetWin_0. Error = 0        
exit status 2```

This is caused by double nil return here: 

```go
// in func(s *windowsSystemTray) bounds() (*Rect, error)
	flyoutOpen := !w32.RectInRect(bounds, &taskbarRect.Rc)
	flyoutOpen := !w32.RectInRect(bounds, &taskbarRect.Rc)
	if flyoutOpen {
		return nil, nil
	}
```

### To Reproduce

Buidl and run the below code on windows, then move the icon in the sys tray to the flyout thingy and then left click the sys tray icon

```go

package main

import (
	_ "embed"
	"log"

	"github.com/wailsapp/wails/v3/pkg/application"
	"github.com/wailsapp/wails/v3/pkg/icons"
)

func main() {
	app := application.New(application.Options{
		Name:        "Systray Demo",
		Description: "A demo of the Systray API",
		Assets:      application.AlphaAssets,
	})

	systemTray := app.NewSystemTray()

	window := app.NewWebviewWindowWithOptions(application.WebviewWindowOptions{
		Width:         400,
		Height:        400,
		Frameless:     false,
		AlwaysOnTop:   true,
		Hidden:        true,
		DisableResize: true,
		ShouldClose: func(window *application.WebviewWindow) bool {
			window.Hide()
			return false
		},
		Windows: application.WindowsWindow{
			HiddenOnTaskbar: false,
		},
		KeyBindings: map[string]func(window *application.WebviewWindow){
			"F12": func(window *application.WebviewWindow) {
				systemTray.OpenMenu()
			},
		},
	})

	systemTray.SetIcon(icons.SystrayLight)
	systemTray.SetDarkModeIcon(icons.SystrayLight)

	myMenu := app.NewMenu()
	myMenu.Add("Wails").SetBitmap(icons.WailsLogoBlackTransparent).SetEnabled(false)

	myMenu.Add("Show Window").OnClick(func(ctx *application.Context) {
		window.Show()
	})

	myMenu.AddSeparator()
	myMenu.Add("Quit").OnClick(func(ctx *application.Context) {
		app.Quit()
	})

	systemTray.SetMenu(myMenu)

	err := app.Run()
	if err != nil {
		log.Fatal(err)
	}
}


### Expected behaviour

The application should open the systray menu and not crash

### Screenshots

_No response_

### Attempted Fixes

_No response_

### System Details

```shell
wails3 doctor


          Wails Doctor
                                


# Build Environment
Wails CLI      | v3.0.0-alpha.3
Go Version     | go1.22.0
Revision       | 12d12a33dec1d31f487b70f87bc31e80252f327c
Modified       | false
-buildmode     | exe
-compiler      | gc
CGO_ENABLED    | 0
DefaultGODEBUG | httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
GOAMD64        | v1
GOARCH         | amd64
GOOS           | windows
vcs            | git
vcs.modified   | false
vcs.revision   | 12d12a33dec1d31f487b70f87bc31e80252f327c
vcs.time       | 2024-02-21T12:40:32Z

# System
Name              | Windows 10 Pro
Version           | 2009 (Build: 22631)
ID                | 23H2
Branding          | Windows 11 Pro
Platform          | windows
Architecture      | amd64
Go WebView2Loader | true
NSIS              | Not Installed
WebView2 Version  | 121.0.2277.128
CPU               | AMD Ryzen 7 3700X 8-Core Processor
GPU 1             | Microsoft Remote Display Adapter (Microsoft) - Driver: 10.0.22621.2861
GPU 2             | NVIDIA GeForce RTX 2070 SUPER (NVIDIA) - Driver: 31.0.15.3623
Memory            | 32GB

# Diagnosis
 SUCCESS  Your system is ready for Wails development!
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tw1nk**
# Description

Removes an unnessecary check which returned a double nil wich in turned causes a crash if systray doesn't have an attached window.

Fixes #3270

## Type of change
  
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

I ran the code referenced in #3270 and it didn't crash.  

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration using `wails doctor`.

- [x] Windows
- [x] macOS
- [x] Linux
  
## Test Configuration

# Build Environment
Wails CLI      | v3.0.0-alpha.3
Go Version     | go1.22.0
Revision       | 12d12a33dec1d31f487b70f87bc31e80252f327c
Modified       | false
-buildmode     | exe
-compiler      | gc
CGO_ENABLED    | 0
DefaultGODEBUG | httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
GOAMD64        | v1
GOARCH         | amd64
GOOS           | windows
vcs            | git
vcs.modified   | false
vcs.revision   | 12d12a33dec1d31f487b70f87bc31e80252f327c
vcs.time       | 2024-02-21T12:40:32Z

# System
Name              | Windows 10 Pro
Version           | 2009 (Build: 22631)
ID                | 23H2
Branding          | Windows 11 Pro
Platform          | windows
Architecture      | amd64
Go WebView2Loader | true
NSIS              | Not Installed
WebView2 Version  | 121.0.2277.128
CPU               | AMD Ryzen 7 3700X 8-Core Processor
GPU 1             | Microsoft Remote Display Adapter (Microsoft) - Driver: 10.0.22621.2861
GPU 2             | NVIDIA GeForce RTX 2070 SUPER (NVIDIA) - Driver: 31.0.15.3623
Memory            | 32GB

# Diagnosis
SUCCESS  Your system is ready for Wails development!

# Checklist:

- [ ] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [x] My code follows the general coding style of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by leaanthony** [comment]
Thanks 🙏 Please could you add an entry to the changelog located at `mkdocs-website/docs/changelog.md`? Thanks!
What's a little unusual is if the icon is in the flyout, the left and right buttons place the menu in different places...

**Review by leaanthony — APPROVED** [review]

**Comment by leaanthony** [comment]
You'll need to revert that last commit and force push

**Comment by leaanthony** [comment]
@tw1nk ☝️

**Comment by tw1nk** [comment]
> You'll need to revert that last commit and force push
> @tw1nk ☝️

done. I think I might accidentally clicked synk branch in GitHub.

File: v3/pkg/application/systemtray_windows.go [hunk 1]
```diff
@@ -4,10 +4,11 @@ package application
 
 import (
 	"fmt"
-	"github.com/wailsapp/wails/v3/pkg/icons"
 	"syscall"
 	"unsafe"
 
+	"github.com/wailsapp/wails/v3/pkg/icons"
```
Comment (tmclane) [inline v3/pkg/application/systemtray_windows.go:10]: A bit pedantic but would you move this all the way down to the rest of the local imports please?

File: v3/pkg/application/systemtray_windows.go [hunk 2]
```diff
@@ -64,25 +57,45 @@ func (s *windowsSystemTray) positionWindow(window *WebviewWindow, offset int) er
...
 		window.SetRelativePosition(newX, offset)
 	case w32.ABE_RIGHT:
-		if trayBounds != nil && trayBounds.Y-(window.Height()/2) <= newY {
+		if iconIsInTrayBounds && trayBounds.Y-(window.Height()/2) <= newY {
 			newY = trayBounds.Y - (window.Height() / 2)
 		}
 		window.SetRelativePosition(screenBounds.Width-window.Width()-offset, newY)
 	case w32.ABE_BOTTOM:
-		if trayBounds != nil && trayBounds.X-(window.Width()/2) <= newX {
+		if iconIsInTrayBounds && trayBounds.X-(window.Width()/2) <= newX {
```
Comment (tmclane) [inline v3/pkg/application/systemtray_windows.go:98]: All of these cases could be handled by a single check above for !iconIsInTrayBounds and bailing

File: v3/pkg/application/systemtray_windows.go [hunk 3]
```diff
@@ -117,6 +122,22 @@ func (s *windowsSystemTray) bounds() (*Rect, error) {
 	}, nil
 }
 
+func (s *windowsSystemTray) iconIsInTrayBounds() (bool, error) {
```
Comment (tmclane) [inline v3/pkg/application/systemtray_windows.go:125]: I'd recommend just returning bool here so you can just use the function call instead of making a local variable with the result named the same thing.

File: v3/pkg/application/systemtray_windows.go (hunk 1 above)
Comment (leaanthony) [reply v3/pkg/application/systemtray_windows.go:10]: These get shifted around all the time due to editor preference. Let's look at that separately. Perhaps a .editor file will help, may not 😅

File: v3/pkg/application/systemtray_windows.go (hunk 3 above)
Comment (leaanthony) [reply v3/pkg/application/systemtray_windows.go:125]: We do need to handle that error though.

File: v3/pkg/application/systemtray_windows.go (hunk 2 above)
Comment (leaanthony) [reply v3/pkg/application/systemtray_windows.go:98]: Yeah, we could wrap the switch in an if. You ok with that @tw1nk ? 🙏

**Review by leaanthony — CHANGES_REQUESTED** [review]
Just a small change if that's ok 🙏

**Comment by leaanthony** [comment]
We can refactor a bit of this later. No need to wait for now. Thanks @tw1nk
