### PR TITLE
Init GTK in `NewFrontend`, not `init`

### LINKED ISSUE #2628: Linux Wails app exits if $DISPLAY not set or valid instead of returning error.
### Description

Wails on Linux quits if $DISPLAY is not set before running the first line of main()

We'd like to be able to take a fallback action (e.g. offer a cli with prompt - or just a customised warning )

### To Reproduce

1. wails init -n nodisplay -t vanilla
2.  cd nodisplay/
3. wails build
4. unset DISPLAY
5. ./build/bin/nodisplay 

### Expected behaviour

I expected 
                println("Error:", err.Error())
to be reached.

### Screenshots

nodisplay$ ./build/bin/nodisplay 
Unable to init server: Could not connect: Connection refused

(nodisplay:43810): Gtk-WARNING **: 10:16:58.531: cannot open display: 

### Attempted Fixes

I added a fmt.print() to the first line of main() - it is never called.
I tried to find where 
`Unable to init server: Could not connect: Connection refused`
is printed - I failed to find it.
We asked for advice on Discord.

### System Details

```shell
nodisplay$ wails doctor
Wails CLI v2.4.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | Debian GNU/Linux
Version      | 11              
ID           | debian          
Go Version   | go1.19.1        
Platform     | linux           
Architecture | amd64           

# Wails

Version         | v2.4.1
Package Manager | apt   

# Dependencies

Dependency | Package Name          | Status    | Version                
*docker    | docker.io             | Available | 20.10.5+dfsg1-1+deb11u2
gcc        | build-essential       | Installed | 10.2.1                 
libgtk-3   | libgtk-3-dev          | Installed | 3.24.24-4+deb11u2      
libwebkit  | libwebkit2gtk-4.0-dev | Installed | 2.38.5-1~deb11u1       
npm        | npm                   | Installed | 9.5.1                  
*nsis      | nsis                  | Available | 3.06.1-1               
pkg-config | pkg-config            | Installed | 0.29.2                 
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details: 
  - docker: sudo apt install docker.io
  - nsis: sudo apt install nsis

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

### Additional context

I understand that without a display wails can't function - but I do feel that an app should be given a chance to report, log, perhaps even fix or work around the error itself rather than the whole app bailing.

Our app is a service with status display - the display is the least important part!

### PR DESCRIPTION
**Pull request by phildrip**
# Description

So that apps that have a headless / non-gui mode will be able to run, since they needn't call `NewFrontend` (which is called by `CreateApp`). Previously, `init()` would call `C.gtk_init` regardless of whether CreateApp was called.

Also, we call `C.gtk_init_check` and check the return value (and panic on failure), instead of `C.gtk_init`, since `gtk_init` just exits the process if it fails, without a sensible error message.

Fixes #2628.

Inspired by #2629, but slightly cleaner imho.

## Type of change
  
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Unset `DISPLAY` env var  
Run our app (which has a `--headless` flag) in headless mode, and it runs ok. Before the change, it would exit.
Run the app without the `--headless` flag, and see a stacktrace:
```
panic: failed to init GTK

goroutine 1 [running, locked to thread]:
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend.func1()
        /home/phil/go/pkg/mod/github.com/phildrip/wails/v2@v2.0.0-20230823104117-04b4634f4a50/internal/frontend/desktop/linux/frontend.go:143 +0x139
sync.(*Once).doSlow(0xc0001a8a20?, 0xc37e20?)
        /usr/local/go/src/sync/once.go:74 +0xbf
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:65
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend({0x159bc40?, 0xc0002d8b70}, 0xc00029d400, 0xc0000134e8, 0xc0001a8a20, {0x1599160?, 0xc0002c8380})
        /home/phil/go/pkg/mod/github.com/phildrip/wails/v2@v2.0.0-20230823104117-04b4634f4a50/internal/frontend/desktop/linux/frontend.go:134 +0x85
github.com/wailsapp/wails/v2/internal/frontend/desktop.NewFrontend(...)
        /home/phil/go/pkg/mod/github.com/phildrip/wails/v2@v2.0.0-20230823104117-04b4634f4a50/internal/frontend/desktop/desktop_linux.go:16
github.com/wailsapp/wails/v2/internal/app.CreateApp(0xc00029d400)
        /home/phil/go/pkg/mod/github.com/phildrip/wails/v2@v2.0.0-20230823104117-04b4634f4a50/internal/app/app_production.go:86 +0x589
github.com/wailsapp/wails/v2/pkg/application.(*Application).Run(0xc00026af20)
        /home/phil/go/pkg/mod/github.com/phildrip/wails/v2@v2.0.0-20230823104117-04b4634f4a50/pkg/application/application.go:57 +0x25
github.com/wailsapp/wails/v2.Run(0xc00029d400?)
        /home/phil/go/pkg/mod/github.com/phildrip/wails/v2@v2.0.0-20230823104117-04b4634f4a50/wails.go:14 +0x9a
```

After setting the `DISPLAY` env var, the app works as normal.

- [ ] Windows
- [ ] macOS
- [x] Linux
  
## Test Configuration
output from `wails doctor`:
```                                
          Wails Doctor          
                                

                                                                                                                                                                                                                                                                                                                                                           
# Wails
Version         | v2.5.1                                  
Revision        | c2b36de510ce04749343fbe08396438d5244ab48
Modified        | true                                    
Package Manager | apt                                     

# System
┌─────────────────────────┐
| OS           | Ubuntu   |
| Version      | 22.04    |
| ID           | ubuntu   |
| Go Version   | go1.21.0 |
| Platform     | linux    |
| Architecture | amd64    |
└─────────────────────────┘

# Dependencies
┌──────────────────────────────────────────────────────────────────────────┐
| Dependency | Package Name          | Status    | Version                 |
| *docker    | docker.io             | Installed | 20.10.21                |
| gcc        | build-essential       | Installed | 12.9ubuntu3             |
| libgtk-3   | libgtk-3-dev          | Installed | 3.24.33-1ubuntu2        |
| libwebkit  | libwebkit2gtk-4.0-dev | Installed | 2.40.5-0ubuntu0.22.04.1 |
| npm        | npm                   | Installed | 8.19.4                  |
| *nsis      | nsis                  | Available | 3.08-2                  |
| pkg-config | pkg-config            | Installed | 0.29.2-1ubuntu3         |
└──────────────────────── * - Optional Dependency ─────────────────────────┘

# Diagnosis
Optional package(s) installation details: 
  - nsis: sudo apt install nsis

 SUCCESS  Your system is ready for Wails development!
```

# Checklist:

- [x] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [x] My code follows the general coding style of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: v2/internal/frontend/desktop/linux/frontend.go [hunk 1]
```diff
@@ -126,18 +130,19 @@ func (f *Frontend) WindowClose() {
...
 
-	C.gtk_init(nil, nil)
-}
+		// Set GDK_BACKEND=x11 if currently unset and XDG_SESSION_TYPE is unset, unspecified or x11 to prevent warnings
+		if os.Getenv("GDK_BACKEND") == "" && (os.Getenv("XDG_SESSION_TYPE") == "" || os.Getenv("XDG_SESSION_TYPE") == "unspecified" || os.Getenv("XDG_SESSION_TYPE") == "x11") {
+			_ = os.Setenv("GDK_BACKEND", "x11")
+		}
 
-func NewFrontend(ctx context.Context, appoptions *options.App, myLogger *logger.Logger, appBindings *binding.Bindings, dispatcher frontend.Dispatcher) *Frontend {
+		if ok := C.gtk_init_check(nil, nil); ok != 1 {
```
Comment (lyimmi) [inline v2/internal/frontend/desktop/linux/frontend.go:142]: Could the set `g_set_prgname` name call moved before the init? It would work better if it's set before the init.

**Comment by lyimmi** [comment]
Could the `g_set_prgname` call moved before the init?
It would work better if it's set before the init.

**Comment by phildrip** [comment]
I expect so, but I don't understand how that would affect things. How would it work better? It seems unrelated to the bugfix...

**Comment by lyimmi** [comment]
I'm sorry the prg_name would be working better if it's set before gtk_init.

It's not related to the bug at all. Just thought if the gtk_init is moved we could move set_prgname to a better place in one PR. That's all.

**Review by leaanthony — APPROVED** [review]
Thanks 🙏

File: v2/internal/frontend/desktop/linux/frontend.go [hunk 2]
```diff
@@ -126,18 +130,19 @@ func (f *Frontend) WindowClose() {
...
-func init() {
-	runtime.LockOSThread()
-
-	// Set GDK_BACKEND=x11 if currently unset and XDG_SESSION_TYPE is unset, unspecified or x11 to prevent warnings
-	if os.Getenv("GDK_BACKEND") == "" && (os.Getenv("XDG_SESSION_TYPE") == "" || os.Getenv("XDG_SESSION_TYPE") == "unspecified" || os.Getenv("XDG_SESSION_TYPE") == "x11") {
-		_ = os.Setenv("GDK_BACKEND", "x11")
-	}
+func NewFrontend(ctx context.Context, appoptions *options.App, myLogger *logger.Logger, appBindings *binding.Bindings, dispatcher frontend.Dispatcher) *Frontend {
+	initOnce.Do(func() {
+		runtime.LockOSThread()
```
Comment (stffabi) [inline v2/internal/frontend/desktop/linux/frontend.go:135]: I',

**Comment by leaanthony** [comment]
Looking to do a release end of the week. Thanks for your patience. In the meantime you can always use the master branch so there shouldn't be any reason for you to be blocked.
